from __future__ import annotations

import re

import torch
import torch.nn as nn

import data_structure.Category as cat
from triton_compile.launch import launch


class TritonModule(nn.Module):
    def __init__(self, term: cat.Morphism, kernel_sources: tuple[str, ...]) -> None:
        super().__init__()
        self.term = term
        self.kernel_sources = kernel_sources
        self._kernels_by_node: dict[int, object] | None = None

    def forward(self, *xs: torch.Tensor) -> torch.Tensor:
        if not torch.cuda.is_available():
            raise RuntimeError(
                "TritonModule.forward requires a CUDA GPU. "
                "Compilation works on CPU; execution does not."
            )
        if self._kernels_by_node is None:
            self._kernels_by_node = _bind_kernels(self.term, self.kernel_sources)
        result = launch(self.term, self._kernels_by_node, xs)
        return result[0] if len(result) == 1 else result


def _bind_kernels(
    term: cat.Morphism,
    sources: tuple[str, ...],
) -> dict[int, object]:
    broadcasts = _collect_broadcasts(term)
    if len(broadcasts) != len(sources):
        raise RuntimeError(
            f"kernel count {len(sources)} != broadcast count {len(broadcasts)}"
        )
    return {id(b): _compile_source(src) for b, src in zip(broadcasts, sources)}


def _collect_broadcasts(term: cat.Morphism) -> list[cat.Broadcasted]:
    out: list[cat.Broadcasted] = []
    _collect(term, out)
    return out


def _collect(term: cat.Morphism, out: list[cat.Broadcasted]) -> None:
    match term:
        case cat.Rearrangement():
            return
        case cat.ProductOfMorphisms():
            for sub in term.content:
                _collect(sub, out)
        case cat.Composed():
            for sub in term.content:
                _collect(sub, out)
        case cat.Block():
            _collect(term.body, out)
        case cat.Broadcasted():
            out.append(term)


_KERNEL_NAME_RE = re.compile(r"^def (_[a-z_]+_kernel)\(", re.MULTILINE)


def _compile_source(src: str) -> object:
    match = _KERNEL_NAME_RE.search(src)
    if not match:
        raise RuntimeError(f"No kernel function name in source:\n{src[:200]}")
    name = match.group(1)
    namespace: dict[str, object] = {}
    exec(src, namespace)  # noqa: S102 - generated by codegen
    return namespace[name]
