from __future__ import annotations

import torch
import torch.nn as nn

import data_structure.Category as cat


class TritonModule(nn.Module):
    def __init__(self, term: cat.Morphism, kernel_sources: tuple[str, ...]) -> None:
        super().__init__()
        self.term = term
        self.kernel_sources = kernel_sources
        # Lazy: do not exec sources until forward() on CUDA.
        self._kernels: tuple[object, ...] | None = None

    def forward(self, *xs: torch.Tensor) -> torch.Tensor:
        if not torch.cuda.is_available():
            raise RuntimeError(
                "TritonModule.forward requires a CUDA GPU. "
                "Compilation works on CPU; execution does not."
            )
        if self._kernels is None:
            self._kernels = tuple(_compile_source(src) for src in self.kernel_sources)
        return _run(self.term, self._kernels, xs)


def _compile_source(src: str) -> object:
    import re

    match = re.search(r"^def (_[a-z_]+_kernel)\(", src, re.MULTILINE)
    if not match:
        raise RuntimeError(f"No kernel function name in source:\n{src[:200]}")
    name = match.group(1)
    namespace: dict[str, object] = {}
    exec(src, namespace)  # noqa: S102 - generated by codegen
    return namespace[name]


def _run(
    term: cat.Morphism,
    kernels: tuple[object, ...],
    xs: tuple[torch.Tensor, ...],
) -> torch.Tensor:
    raise NotImplementedError(
        "Stage A runtime: launcher for compiled kernels is deferred to Task 15"
    )
